// Reference texts for checking the index's anchors. Written for this test in
// the style of each kind of text, not taken from a source: the academic one
// in the nominal, nested style of a social-science dissertation, the plain
// one like a tabloid or easy-language news item.

export const ACADEMIC_DE = `Die vorliegende Untersuchung verfolgt das Ziel, die bislang in der kommunikationswissenschaftlichen Forschung nur unzureichend berücksichtigten Wechselwirkungen zwischen der institutionellen Verfasstheit politischer Organisationen und der Ausgestaltung ihrer externen Kommunikationsstrategien unter Rückgriff auf ein mehrstufiges, sowohl quantitative als auch qualitative Verfahren integrierendes Forschungsdesign systematisch zu analysieren. Im Zentrum der Betrachtung steht dabei die Frage, inwiefern die Professionalisierung der Öffentlichkeitsarbeit, die sich in der zunehmenden Ausdifferenzierung organisationsinterner Zuständigkeiten manifestiert, mit einer Veränderung der Verständlichkeit der veröffentlichten Texte einhergeht. Hinsichtlich der theoretischen Fundierung wird auf systemtheoretische Ansätze zurückgegriffen, deren Anwendbarkeit auf die spezifischen Bedingungen der Parteienkommunikation allerdings einer kritischen Überprüfung unterzogen werden muss. Die Operationalisierung der Verständlichkeitsdimension erfolgt in Anlehnung an etablierte Lesbarkeitsformeln, wobei deren methodologische Limitationen im Rahmen einer ausführlichen Diskussion berücksichtigt werden.`;

export const PLAIN_DE = `Der Bus fährt ab Montag öfter. Das hat die Stadt am Freitag gesagt. Er kommt dann alle zehn Minuten. Bisher waren es zwanzig. Viele Leute haben sich das gewünscht. Vor allem am Morgen war der Bus oft voll. Jetzt gibt es mehr Platz. Die Fahrt kostet nicht mehr Geld. Das Ticket bleibt gleich. Am Wochenende ändert sich nichts. Dann fährt der Bus wie immer alle halbe Stunde. Wer Fragen hat, kann bei der Stadt anrufen. Die Nummer steht auf der Webseite. Die Stadt will im Sommer prüfen, ob der neue Plan gut ist.`;

/** A typical corporate press release: should land around the press target of 12. */
export const PRESS_DE = `Die Stadtwerke Musterstadt erweitern ihr Angebot im Bereich Elektromobilität und stellen ab dem kommenden Monat zwanzig zusätzliche Ladestationen im gesamten Stadtgebiet zur Verfügung. Mit der Inbetriebnahme der neuen Ladepunkte reagiert das Unternehmen auf die stark gestiegene Nachfrage seiner Kundinnen und Kunden. „Wir sehen die Elektromobilität als zentralen Baustein der Energiewende vor Ort“, erklärt Geschäftsführerin Anna Schmidt. Die Standorte wurden in enger Abstimmung mit der Stadtverwaltung ausgewählt und befinden sich überwiegend in der Nähe von Einkaufsmöglichkeiten und öffentlichen Einrichtungen. Geladen werden kann sowohl mit der Ladekarte der Stadtwerke als auch per App oder Kreditkarte. Der Strom stammt zu hundert Prozent aus erneuerbaren Energien. Weitere Informationen zu Standorten, Preisen und Tarifen finden Interessierte auf der Internetseite der Stadtwerke.`;
